{
 "title": "AiSEG2 - Total",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "使用電力量(EV)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"circuit_daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"電力使用量(EV)(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> yield(name: \"max\")\n"
    }
   ]
  },
  {
   "title": "使用電力量(EV)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"circuit_daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"電力使用量(EV)(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> sum()\n  |> yield(name: \"sum\")\n"
    },
    { "expression": "$EV / $Usage", "type": "math" }
   ]
  },
  {
   "title": "発電量 / 使用電力量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"発電量(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> yield(name: \"max\")\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"使用電力量(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> yield(name: \"max\")\n"
    }
   ]
  },
  {
   "title": "発電量 / 使用電力量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"使用電力量(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> sum()\n  |> yield(name: \"sum\")\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"発電量(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> sum()\n  |> yield(name: \"sum\")\n"
    }
   ]
  },
  {
   "title": "買電量 / 売電量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"買電量(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> yield(name: \"max\")\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"売電量(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> yield(name: \"max\")\n"
    }
   ]
  },
  {
   "title": "買電量 / 売電量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"買電量(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> sum()\n  |> yield(name: \"sum\")\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"売電量(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> sum()\n  |> yield(name: \"sum\")\n"
    }
   ]
  },
  {
   "title": "エアコン使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"circuit_daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"リビングエアコン(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> yield(name: \"max\")\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"circuit_daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"主寝室エアコン(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> yield(name: \"max\")\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"circuit_daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"洋室２エアコン(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> yield(name: \"max\")\n"
    }
   ]
  },
  {
   "title": "エアコン使用量 (合計)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B + $C", "type": "math" }
   ]
  },
  {
   "title": "エアコン使用量 （内訳）",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"circuit_daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"リビングエアコン(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> sum()\n  |> yield(name: \"sum\")\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"circuit_daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"主寝室エアコン(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> sum()\n  |> yield(name: \"sum\")\n"
    },
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"circuit_daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"洋室２エアコン(kWh)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> sum()\n  |> yield(name: \"sum\")\n"
    }
   ]
  },
  {
   "title": "湯(L)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"湯(L)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> yield(name: \"max\")\n"
    }
   ]
  },
  {
   "title": "ガス(㎥)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"daily_total\")\n  |> filter(fn: (r) => r[\"detail-section\"] == \"ガス(㎥)\")\n  |> aggregateWindow(every: 1d, fn: max)\n  |> yield(name: \"max\")\n"
    }
   ]
  }
 ]
}